### ISSUE TITLE
vpr_plot_profile() 

### ISSUE THREAD

**Issue by kevinsorochan** [Echisholm21/vprr#22]
The function vpr_plot_profile() is not working properly when the argument plot_conc = T. I think there is an issue with the column name for the plankton concentration variable: it should now be conc_m3. Also the y axis should be labelled as 'depth' rather than 'pressure'.

**Comment by Echisholm21** [comment]
Can you send me a sample of your data so I can try to reproduce the error locally? an RData file of what you are attempting to plot would be perfect.

**Comment by kevinsorochan** [comment]
There is a column name issue, but it was not conc_m3, rather 'pressure' (it should be depth).

**Comment by Echisholm21** [comment]
Issue now solved.

The concentration plots were relying on 'pressure' which was not a variable in the dataframe taxa_conc_n

All plots in vpr_plot_profile now rely on 'depth' (not pressure)

I also added a stop so if you attempt to plot a dataframe without a 'depth' variable you will get an error reminding you it is required. This should hopefully prevent similar issues in the future.
