### ISSUE TITLE
vpr_autoid_create() does not accommodate for empty misclassification files 

### ISSUE THREAD

**Issue by kevinsorochan** [Echisholm21/vprr#24]
When there is an empty reclassification file and empty misclassification file an empty newaid file is created. This is a problem of course, if there are existing rois in the VP output for that category. I don't think that I have ran into this problem in the past because it requires that all images within a category be identified perfectly by VP 🤣. 

I have created a quick fix and hope that it works properly - I also added day and hour arguments to get it to run properly in my application. There needs to be some consolidation and clean up as well. I'm happy to work on this... 

The fix just involves an if statement. I tried to attached the full function in previous edits of this post, but it was not working properly. 

`if(length(mis_roi) == 0) {
        
        aid_new <- aid_list_old
        
        ind <- vector()
        
        }`

**Comment by kevinsorochan** [comment]
The same thing needs to be done with the meas files...
[vpr_auto_create_ks.txt](https://github.com/Echisholm21/vprr/files/6831977/vpr_auto_create_ks.txt)

**Comment by Echisholm21** [comment]
I copied the updates made in vpr_auto_create_ks.txt into the function `vpr_autoid_create()` with notes

The meas file loop still needs to be updated to match

(!) Not yet tested

**Comment by Echisholm21** [comment]
I've run some basic testing on this new functionality and it seems to be in order. aid and aidmeas files are now appropriately carried over if misclassified files are empty (in case there were no mistakes made by VP). 'reclassified' ROIs are still added to the files in this case.
